/**
 * ALL tunable numbers live here. Game logic must read BALANCE — no magic numbers.
 *
 * ---------------------------------------------------------------------------
 * FACTION BUDGET  (each village: bonuses = 100, penalties = 100, net 0)
 * ---------------------------------------------------------------------------
 */

export const VILLAGE_IDS = ["leaf", "sand", "mist", "cloud", "stone"] as const;
export type VillageId = (typeof VILLAGE_IDS)[number];

export const UNIT_IDS = ["genin", "chunin", "illusion", "cavalry", "siege", "anbu"] as const;
export type UnitId = (typeof UNIT_IDS)[number];

export const COMBAT_STYLES = ["taijutsu", "ninjutsu", "genjutsu", "siege", "elite"] as const;
export type CombatStyle = (typeof COMBAT_STYLES)[number];

export const TERRAINS = [
  "plains",
  "forest",
  "hill",
  "mountain",
  "river",
  "scorched",
  "desert",
] as const;
export type Terrain = (typeof TERRAINS)[number];

export const BUILDING_IDS = ["academy", "market", "wall", "temple", "hospital"] as const;
export type BuildingId = (typeof BUILDING_IDS)[number];

export const TECH_IDS = ["line", "heal", "teleport", "subjugate"] as const;
export type TechId = (typeof TECH_IDS)[number];

export const SKILL_BRANCHES = ["war", "econ", "scout"] as const;
export type SkillBranch = (typeof SKILL_BRANCHES)[number];

export const TACTIC_IDS = ["assault", "defend", "flank"] as const;
export type TacticId = (typeof TACTIC_IDS)[number];

export const DIFFICULTY_IDS = ["human", "easy", "medium", "hard"] as const;
export const DIFFICULTIES = DIFFICULTY_IDS;
export type Difficulty = (typeof DIFFICULTY_IDS)[number];

export const FACTION_BUDGET = [
  {
    id: "leaf",
    name: "Лист",
    bonuses: [
      {
        pts: 25,
        text: "+25% опыта командирам",
      },
      {
        pts: 20,
        text: "союзы дешевле на 40%",
      },
      {
        pts: 20,
        text: "универсальные юниты без штрафа местности",
      },
      {
        pts: 15,
        text: "+2 генина на старте",
      },
      {
        pts: 20,
        text: "репутация стартует выше, проще дипломатия",
      },
    ],
    penalties: [
      {
        pts: 30,
        text: "нет уникального боевого трюка",
      },
      {
        pts: 25,
        text: "нет бонуса местности",
      },
      {
        pts: 20,
        text: "обычная скорость",
      },
      {
        pts: 25,
        text: "обычная экономика",
      },
    ],
  },
  {
    id: "sand",
    name: "Песок",
    bonuses: [
      {
        pts: 25,
        text: "пустыня даёт полный доход",
      },
      {
        pts: 25,
        text: "+1 к дальности хода",
      },
      {
        pts: 25,
        text: "щит песка −30% первого урона за бой",
      },
      {
        pts: 25,
        text: "нет штрафа движения по пустыне",
      },
    ],
    penalties: [
      {
        pts: 30,
        text: "не-пустынные точки −20% дохода",
      },
      {
        pts: 20,
        text: "постройки +15% стоимости",
      },
      {
        pts: 25,
        text: "−10% HP юнитов",
      },
      {
        pts: 25,
        text: "репутация стартует ниже",
      },
    ],
  },
  {
    id: "mist",
    name: "Туман",
    bonuses: [
      {
        pts: 30,
        text: "игнорирует зону контроля врага",
      },
      {
        pts: 30,
        text: "засада в лесу +50% урона первым ударом",
      },
      {
        pts: 20,
        text: "видимость противника −1",
      },
      {
        pts: 20,
        text: "+25% дохода с лесных точек",
      },
    ],
    penalties: [
      {
        pts: 30,
        text: "−20% урона на равнине",
      },
      {
        pts: 25,
        text: "+15% стоимости юнитов",
      },
      {
        pts: 25,
        text: "−15% дохода столицы",
      },
      {
        pts: 20,
        text: "гарнизоны −20% защиты",
      },
    ],
  },
  {
    id: "cloud",
    name: "Облако",
    bonuses: [
      {
        pts: 25,
        text: "кавалерия с хода 1, +1 хода кавалерии",
      },
      {
        pts: 30,
        text: "+2 инициативы всем",
      },
      {
        pts: 20,
        text: "элита дешевле на 15%",
      },
      {
        pts: 25,
        text: "+15% атаки",
      },
    ],
    penalties: [
      {
        pts: 40,
        text: "−20% дохода рё",
      },
      {
        pts: 30,
        text: "+20% стоимости обычных юнитов",
      },
      {
        pts: 30,
        text: "−15% защиты",
      },
    ],
  },
  {
    id: "stone",
    name: "Камень",
    bonuses: [
      {
        pts: 30,
        text: "постройки −30% стоимости",
      },
      {
        pts: 30,
        text: "гарнизоны +50% защиты",
      },
      {
        pts: 20,
        text: "+20% защиты на холмах",
      },
      {
        pts: 20,
        text: "+10% защиты юнитов",
      },
    ],
    penalties: [
      {
        pts: 35,
        text: "−1 к дальности хода",
      },
      {
        pts: 25,
        text: "медленный старт, −10% дохода до 8 хода",
      },
      {
        pts: 20,
        text: "−2 инициативы",
      },
      {
        pts: 20,
        text: "союзы дороже на 40%",
      },
    ],
  },
] as const;

export const BALANCE = {
  saveVersion: 5,
  map: {
    presets: {
      duel: {
        w: 24,
        h: 18,
        playersMin: 2,
        playersMax: 2,
        turnLimit: 90,
        capitalDistMin: 18,
        capitalDistMax: 23,
        neutralsPerPlayer: 4,
        resourcesPerPlayer: 4,
      },
      standard: {
        w: 28,
        h: 22,
        playersMin: 3,
        playersMax: 4,
        turnLimit: 100,
        capitalDistMin: 16,
        capitalDistMax: 22,
        neutralsPerPlayer: 4,
        resourcesPerPlayer: 4,
      },
      large: {
        w: 34,
        h: 26,
        playersMin: 5,
        playersMax: 6,
        turnLimit: 120,
        capitalDistMin: 15,
        capitalDistMax: 22,
        neutralsPerPlayer: 4,
        resourcesPerPlayer: 5,
      },
      continent: {
        w: 38,
        h: 30,
        playersMin: 7,
        playersMax: 8,
        turnLimit: 140,
        capitalDistMin: 14,
        capitalDistMax: 22,
        neutralsPerPlayer: 5,
        resourcesPerPlayer: 5,
      },
    },
    genAttempts: 140,
    hexSize: 56,
    moveCost: {
      plains: 1,
      forest: 1,
      hill: 2,
      mountain: 99,
      river: 2,
      scorched: 1,
      desert: 1,
    },
    desertMovePenalty: 1,
    mountainElev: 0.78,
    hillElev: 0.62,
    forestMoisture: 0.68,
    desertMoisture: 0.3,
    riverCountMin: 1,
    riverCountMax: 3,
  },
  colors: {
    bg: "#12151c",
    bgElev: "#181c26",
    bgPanel: "#161a23",
    ink: "#c8ccd4",
    inkMuted: "#8b909c",
    inkSubtle: "#5c6270",
    line: "rgba(200,204,212,0.14)",
    lineStrong: "rgba(200,204,212,0.28)",
    contested: "#c9a066",
    terrain: {
      plains: ["#2f3c34", "#3a4a3e"],
      forest: ["#1f4434", "#275840"],
      hill: ["#43382c", "#524636"],
      mountain: ["#3a3e48", "#4c515c"],
      river: ["#1e4258", "#27546c"],
      scorched: ["#3a2c22", "#453428"],
      desert: ["#4a4028", "#5a4c30"],
    },
    villages: {
      leaf: {
        accent: "#3d8b5a",
        glow: "#6ed48a",
        kanji: "木",
      },
      sand: {
        accent: "#c9a227",
        glow: "#e8cc5a",
        kanji: "砂",
      },
      mist: {
        accent: "#6b8cae",
        glow: "#9ab6d4",
        kanji: "霧",
      },
      cloud: {
        accent: "#7ec8e3",
        glow: "#b6e4f4",
        kanji: "雲",
      },
      stone: {
        accent: "#c47a3a",
        glow: "#e09a5c",
        kanji: "岩",
      },
    },
  },
  villages: {
    leaf: {
      id: "leaf",
      name: "Лист",
      nameJp: "木ノ葉",
      commanderXp: 1.25,
      allianceCostMult: 0.6,
      startGeninBonus: 2,
      startRep: 60,
      moveDelta: 0,
      initiativeDelta: 0,
      attackMult: 1,
      defenseMult: 1,
      hpMult: 1,
      unitCostMult: 1,
      buildingCostMult: 1,
      ryoIncomeMult: 1,
      capitalIncomeMult: 1,
      desertIncomeMult: 0.5,
      forestIncomeMult: 1,
      otherIncomeMult: 1,
      sandShield: 0,
      ignoreZoc: false,
      forestAmbush: 0,
      visionPenaltyToEnemies: 0,
      plainsDamageMult: 1,
      garrisonDefMult: 1,
      hillDefMult: 1,
      cavalryFromStart: false,
      eliteCostMult: 1,
      slowStartTurns: 0,
      slowStartIncome: 1,
      desertMoveFree: false,
    },
    sand: {
      id: "sand",
      name: "Песок",
      nameJp: "砂",
      commanderXp: 1,
      allianceCostMult: 1.1,
      startGeninBonus: 0,
      startRep: 40,
      moveDelta: 1,
      initiativeDelta: 0,
      attackMult: 1,
      defenseMult: 1,
      hpMult: 0.9,
      unitCostMult: 1,
      buildingCostMult: 1.15,
      ryoIncomeMult: 1,
      capitalIncomeMult: 1,
      desertIncomeMult: 1,
      forestIncomeMult: 1,
      otherIncomeMult: 0.8,
      sandShield: 0.3,
      ignoreZoc: false,
      forestAmbush: 0,
      visionPenaltyToEnemies: 0,
      plainsDamageMult: 1,
      garrisonDefMult: 1,
      hillDefMult: 1,
      cavalryFromStart: false,
      eliteCostMult: 1,
      slowStartTurns: 0,
      slowStartIncome: 1,
      desertMoveFree: true,
    },
    mist: {
      id: "mist",
      name: "Туман",
      nameJp: "霧",
      commanderXp: 1,
      allianceCostMult: 1,
      startGeninBonus: 0,
      startRep: 50,
      moveDelta: 0,
      initiativeDelta: 0,
      attackMult: 1,
      defenseMult: 1,
      hpMult: 1,
      unitCostMult: 1.15,
      buildingCostMult: 1,
      ryoIncomeMult: 1,
      capitalIncomeMult: 0.85,
      desertIncomeMult: 0.5,
      forestIncomeMult: 1.25,
      otherIncomeMult: 1,
      sandShield: 0,
      ignoreZoc: true,
      forestAmbush: 0.5,
      visionPenaltyToEnemies: 1,
      plainsDamageMult: 0.8,
      garrisonDefMult: 0.8,
      hillDefMult: 1,
      cavalryFromStart: false,
      eliteCostMult: 1,
      slowStartTurns: 0,
      slowStartIncome: 1,
      desertMoveFree: false,
    },
    cloud: {
      id: "cloud",
      name: "Облако",
      nameJp: "雲",
      commanderXp: 1,
      allianceCostMult: 1,
      startGeninBonus: 0,
      startRep: 50,
      moveDelta: 0,
      initiativeDelta: 2,
      attackMult: 1.15,
      defenseMult: 0.85,
      hpMult: 1,
      unitCostMult: 1.2,
      buildingCostMult: 1,
      ryoIncomeMult: 0.8,
      capitalIncomeMult: 1,
      desertIncomeMult: 0.5,
      forestIncomeMult: 1,
      otherIncomeMult: 1,
      sandShield: 0,
      ignoreZoc: false,
      forestAmbush: 0,
      visionPenaltyToEnemies: 0,
      plainsDamageMult: 1,
      garrisonDefMult: 1,
      hillDefMult: 1,
      cavalryFromStart: true,
      eliteCostMult: 0.85,
      slowStartTurns: 0,
      slowStartIncome: 1,
      desertMoveFree: false,
    },
    stone: {
      id: "stone",
      name: "Камень",
      nameJp: "岩",
      commanderXp: 1,
      allianceCostMult: 1.4,
      startGeninBonus: 0,
      startRep: 50,
      moveDelta: -1,
      initiativeDelta: -2,
      attackMult: 1,
      defenseMult: 1.1,
      hpMult: 1,
      unitCostMult: 1,
      buildingCostMult: 0.7,
      ryoIncomeMult: 1,
      capitalIncomeMult: 1,
      desertIncomeMult: 0.5,
      forestIncomeMult: 1,
      otherIncomeMult: 1,
      sandShield: 0,
      ignoreZoc: false,
      forestAmbush: 0,
      visionPenaltyToEnemies: 0,
      plainsDamageMult: 1,
      garrisonDefMult: 1.5,
      hillDefMult: 1.2,
      cavalryFromStart: false,
      eliteCostMult: 1,
      slowStartTurns: 8,
      slowStartIncome: 0.9,
      desertMoveFree: false,
    },
  },
  income: {
    capitalRyo: 100,
    capitalSupplies: 20,
    capitalChakra: 3,
    settlementRyo: 25,
    settlementSupplies: 8,
    resourceYield: 40,
    capturedPenaltyTurns: 3,
    capturedPenaltyRate: 0.5,
    trailingShare: 0.3,
    trailingIncomeBonus: 0.2,
    upkeepPerUnits: 5,
    upkeepSupplies: 1,
    desertionFrac: 0.15,
    startRyo: 150,
    startSupplies: 30,
    startChakra: 5,
  },
  units: {
    overCap: 10,
    overCapCostMult: 1.15,
    baseMove: 3,
    cavalryMoveBonus: 1,
    vision: 2,
    commanderVision: 3,
    settlementVision: 2,
    capitalVision: 3,
    resourceVision: 1,
    defs: {
      genin: {
        id: "genin",
        name: "Генин",
        style: "taijutsu" as CombatStyle,
        atk: 8,
        def: 6,
        hp: 10,
        ini: 4,
        move: 3,
        costRyo: 20,
        costSupplies: 1,
        costChakra: 0,
        needAcademy: false,
        garrison: false,
      },
      chunin: {
        id: "chunin",
        name: "Чунин",
        style: "ninjutsu" as CombatStyle,
        atk: 11,
        def: 7,
        hp: 12,
        ini: 5,
        move: 3,
        costRyo: 36,
        costSupplies: 2,
        costChakra: 0,
        needAcademy: true,
        garrison: false,
      },
      illusion: {
        id: "illusion",
        name: "Гэндзюцу",
        style: "genjutsu" as CombatStyle,
        atk: 10,
        def: 5,
        hp: 9,
        ini: 6,
        move: 3,
        costRyo: 34,
        costSupplies: 2,
        costChakra: 0,
        needAcademy: true,
        garrison: false,
      },
      cavalry: {
        id: "cavalry",
        name: "Кавалерия",
        style: "taijutsu" as CombatStyle,
        atk: 12,
        def: 5,
        hp: 11,
        ini: 8,
        move: 4,
        costRyo: 42,
        costSupplies: 2,
        costChakra: 0,
        needAcademy: true,
        garrison: false,
      },
      siege: {
        id: "siege",
        name: "Осада",
        style: "siege" as CombatStyle,
        atk: 14,
        def: 4,
        hp: 10,
        ini: 2,
        move: 2,
        costRyo: 50,
        costSupplies: 3,
        costChakra: 0,
        needAcademy: true,
        garrison: false,
      },
      anbu: {
        id: "anbu",
        name: "АНБУ",
        style: "elite" as CombatStyle,
        atk: 16,
        def: 10,
        hp: 14,
        ini: 7,
        move: 3,
        costRyo: 80,
        costSupplies: 3,
        costChakra: 1,
        needAcademy: true,
        garrison: false,
      },
    },
  },
  combat: {
    triangleBonus: 0.3,
    triangle: {
      taijutsu: "ninjutsu",
      ninjutsu: "genjutsu",
      genjutsu: "taijutsu",
    } as Record<string, CombatStyle>,
    damageVariance: 0.1,
    defenseK: 50,
    maxRounds: 8,
    siegeVsGarrison: 0.5,
    firstStrikeInitBonus: 20,
    fogAmbushAtk: 0.65,
    fogAmbushDef: 1.4,
    previewSims: 100,
    previewWarnChance: 0.35,
    retreatLoss: 0.15,
    retreatWinChance: 0.3,
    retreatSims: 40,
    botForecastSims: 24,
    scoutRevealRank: 1,
    arenaTeleportIni: 12,
    arenaSubjugateFrac: 0.2,
    tactics: {
      assault: {
        name: "Натиск",
        atk: 1.25,
        def: 0.8,
        retreatLoss: 0.15,
        noCounterRound1: false,
        text: "+25% урона, −20% защиты",
      },
      defend: {
        name: "Оборона",
        atk: 0.85,
        def: 1.3,
        retreatLoss: 0,
        noCounterRound1: false,
        text: "+30% защиты, −15% урона, отход без потерь",
      },
      flank: {
        name: "Обход",
        atk: 1,
        def: 0.8,
        retreatLoss: 0.15,
        noCounterRound1: true,
        text: "первый раунд без ответа, −20% защиты весь бой",
      },
    },
  },
  influence: {
    settlementRange: 2,
    settlementSelf: 3,
    capitalRange: 3,
    capitalSelf: 4,
    captureTurns: 1,
  },
  buildings: {
    academy: {
      name: "Академия",
      costRyo: 120,
      costSupplies: 50,
      costChakra: 0,
    },
    market: {
      name: "Рынок",
      costRyo: 100,
      costSupplies: 40,
      costChakra: 0,
      ryoBonus: 0.3,
    },
    wall: {
      name: "Стена",
      costRyo: 80,
      costSupplies: 45,
      costChakra: 0,
      garrisonDefBonus: 0.5,
    },
    temple: {
      name: "Храм чакры",
      costRyo: 90,
      costSupplies: 40,
      costChakra: 0,
      chakra: 2,
    },
    hospital: {
      name: "Госпиталь",
      costRyo: 70,
      costSupplies: 40,
      costChakra: 0,
      heal: 0.3,
    },
  },
  diplomacy: {
    napRepMin: 20,
    tradeRepMin: 30,
    allianceRepMin: 45,
    allianceCost: 80,
    tradeRyo: 20,
    tradeIncome: 0.1,
    breakPactRepHit: 25,
    declareWarRepHit: 8,
    startRep: 50,
    lowRepThreshold: 30,
  },
  commanders: {
    secondHireTurn: 20,
    secondHireCostRyo: 200,
    maxLevel: 5,
    xpLevels: [0, 40, 90, 160, 250],
    skillPointsPerLevel: 1,
    xpBattleWin: 12,
    xpBattleLoss: 6,
    xpCapture: 20,
    xpCapital: 40,
    xpKill: 8,
    techChakra: {
      line: 2,
      heal: 2,
      teleport: 3,
      subjugate: 2,
    },
    techCd: {
      line: 4,
      heal: 3,
      teleport: 5,
      subjugate: 4,
    },
    lineDamage: 28,
    lineLen: 3,
    healFrac: 0.35,
    teleportRange: 6,
    defs: {
      leaf_kaen: {
        id: "leaf_kaen",
        village: "leaf",
        name: "Каэн",
        title: "Пламя",
        tech: "line",
        passive: "atk10",
      },
      leaf_shizu: {
        id: "leaf_shizu",
        village: "leaf",
        name: "Шизу",
        title: "Медик",
        tech: "heal",
        passive: "healAfter",
      },
      leaf_shino: {
        id: "leaf_shino",
        village: "leaf",
        name: "Шино",
        title: "Тень",
        tech: "teleport",
        passive: "vision",
      },
      sand_ryusa: {
        id: "sand_ryusa",
        village: "sand",
        name: "Рюса",
        title: "Щит песка",
        tech: "line",
        passive: "shield",
      },
      sand_kugutsu: {
        id: "sand_kugutsu",
        village: "sand",
        name: "Кугуцу",
        title: "Кукловод",
        tech: "subjugate",
        passive: "vsNeutral",
      },
      sand_saifu: {
        id: "sand_saifu",
        village: "sand",
        name: "Сайфу",
        title: "Ветер",
        tech: "teleport",
        passive: "move",
      },
      mist_kiri: {
        id: "mist_kiri",
        village: "mist",
        name: "Кири",
        title: "Скрытый туман",
        tech: "line",
        passive: "ambush",
      },
      mist_silent: {
        id: "mist_silent",
        village: "mist",
        name: "Сайлент",
        title: "Беззвучный",
        tech: "heal",
        passive: "zoc",
      },
      mist_hunter: {
        id: "mist_hunter",
        village: "mist",
        name: "Охотник",
        title: "Тракеры",
        tech: "subjugate",
        passive: "capture",
      },
      cloud_raiko: {
        id: "cloud_raiko",
        village: "cloud",
        name: "Райко",
        title: "Молния",
        tech: "line",
        passive: "ini",
      },
      cloud_sora: {
        id: "cloud_sora",
        village: "cloud",
        name: "Сора",
        title: "Скорость",
        tech: "teleport",
        passive: "move",
      },
      cloud_hei: {
        id: "cloud_hei",
        village: "cloud",
        name: "Хэи",
        title: "Гром",
        tech: "heal",
        passive: "atk10",
      },
      stone_dogan: {
        id: "stone_dogan",
        village: "stone",
        name: "Доган",
        title: "Каменная стена",
        tech: "line",
        passive: "def",
      },
      stone_yogan: {
        id: "stone_yogan",
        village: "stone",
        name: "Йоган",
        title: "Крепость",
        tech: "heal",
        passive: "garrison",
      },
      stone_kokuo: {
        id: "stone_kokuo",
        village: "stone",
        name: "Кокуо",
        title: "Пыль",
        tech: "subjugate",
        passive: "siege",
      },
    },
  },
  skills: {
    war: [
      {
        id: "w1",
        name: "Клинок",
        text: "+15% атаки",
      },
      {
        id: "w2",
        name: "Стойка",
        text: "+15% защиты",
      },
      {
        id: "w3",
        name: "Первый удар",
        text: "отряд действует первым",
      },
      {
        id: "w4",
        name: "Стихия",
        text: "+15% к бонусу треугольника",
      },
      {
        id: "w5",
        name: "Штурм",
        text: "+25% против гарнизонов",
      },
    ],
    econ: [
      {
        id: "e1",
        name: "Казна",
        text: "+15% рё",
      },
      {
        id: "e2",
        name: "Обоз",
        text: "+15% припасов",
      },
      {
        id: "e3",
        name: "Подряд",
        text: "−15% стоимости юнитов",
      },
      {
        id: "e4",
        name: "Печать",
        text: "+1 чакры за ход",
      },
      {
        id: "e5",
        name: "Дисциплина",
        text: "дезертирство вдвое слабее",
      },
    ],
    scout: [
      {
        id: "s1",
        name: "Марш",
        text: "+1 ход",
      },
      {
        id: "s2",
        name: "Дозор",
        text: "+1 обзор",
      },
      {
        id: "s3",
        name: "Обход",
        text: "игнор зоны контроля",
      },
      {
        id: "s4",
        name: "Чаща",
        text: "+25% боя в лесу",
      },
      {
        id: "s5",
        name: "Флаг",
        text: "захват без ожидания",
      },
    ],
    warAtk: 0.15,
    warDef: 0.15,
    warTriangle: 0.15,
    warSiege: 0.25,
    econRyo: 0.15,
    econSupplies: 0.15,
    econUnitCost: 0.15,
    econChakra: 1,
    scoutForest: 0.25,
  },
  garrisons: {
    capitalCount: 10,
    settlementCount: 6,
    resourceCount: 2,
    unit: "genin" as UnitId,
  },
  start: {
    commanderGenin: 6,
  },
  victory: {
    territoryShare: 0.6,
    territoryHoldTurns: 3,
  },
  ai: {
    attackThreshold: 0.8,
    easyMisjudgeMin: 0.6,
    easyMisjudgeMax: 1.4,
    hardIncome: 1.25,
    hirePerTurn: 4,
    targetArmy: 18,
  },
  vision: {
    base: 2,
    fog: true,
    shroudAlpha: 0.62,
  },
  missions: {
    max: 3,
    lifetime: 7,
    spawnStart: 2,
    kinds: {
      scroll: {
        name: "Свиток",
        chakra: 5,
        xp: 18,
        ryo: 0,
        supplies: 0,
        heal: 0,
      },
      shrine: {
        name: "Святилище",
        chakra: 3,
        xp: 12,
        ryo: 0,
        supplies: 0,
        heal: 0.45,
      },
      cache: {
        name: "Тайник",
        chakra: 0,
        xp: 10,
        ryo: 55,
        supplies: 10,
        heal: 0,
      },
      bounty: {
        name: "Охота",
        chakra: 0,
        xp: 22,
        ryo: 90,
        supplies: 0,
        heal: 0,
      },
    },
  },
  fx: {
    moveMs: 170,
    botMoveMs: 100,
    damageMs: 1100,
    flashMs: 480,
    pulseMs: 1800,
    slashMs: 640,
    arenaWalkMs: 560,
    arenaHitMs: 420,
    arenaTechMs: 520,
    arenaShakePx: 8,
    hitStepMs: 540,
  },
};

export const PRESET_LABELS: Record<string, string> = {
  duel: "Дуэль",
  standard: "Стандарт",
  large: "Большая",
  continent: "Континент",
};

export const TERRAIN_LABELS: Record<Terrain, string> = {
  plains: "Равнина",
  forest: "Лес",
  hill: "Холм",
  mountain: "Горы",
  river: "Река",
  scorched: "Выжженная земля",
  desert: "Пустыня",
};

export const STYLE_LABELS: Record<CombatStyle, string> = {
  taijutsu: "Тайдзюцу",
  ninjutsu: "Ниндзюцу",
  genjutsu: "Гэндзюцу",
  siege: "Осада",
  elite: "Элита",
};

export const TECH_LABELS: Record<TechId, string> = {
  line: "Техника линии",
  heal: "Исцеление",
  teleport: "Телепорт",
  subjugate: "Подчинение",
};

export const DIFFICULTY_LABELS: Record<Difficulty, string> = {
  human: "Человек",
  easy: "Лёгкий бот",
  medium: "Средний бот",
  hard: "Сложный бот",
};

export const TACTIC_LABELS: Record<TacticId, string> = {
  assault: "Натиск",
  defend: "Оборона",
  flank: "Обход",
};
